### ISSUE TITLE
Registering tab as N spaces (or literal tab)

### ISSUE THREAD

**Issue by rgbkrk** [SamyPesse/draftjs-prism#2]
Tab is the default behavior currently, it would be great to have this as space insertion similar to codemirror.

**Comment by SamyPesse** [comment]
I agree, but this is not the goal of this module, `draftjs-prism` should only provide the code highlighting, not the keyboard handling.

Since I'm going to work on this for our application at GitBook, I'll probably publish a module like `draftjs-code` to provide helpers for this.

**Comment by SamyPesse** [comment]
@rgbkrk I'm working on [draft-js-code](https://github.com/SamyPesse/draft-js-code) to do this, take a look at the demo: http://samypesse.github.io/draft-js-code/

**Comment by rgbkrk** [comment]
That's a great demo! Thanks.
